### ISSUE TITLE
Disable functionality

### ISSUE THREAD

**Issue by vijaykerure** [ferencb/jqlistbox#12]
@ferencb  There is no such functionality, which can restrict the user to transfer Selected  Listitem To another Listbox and move as well.

**Comment by ferencb** [comment]
@vjuser would you like to setup a custom callback which is executed before the item is moved and if returns false the item won't moved?

**Comment by rablinz** [comment]
Is it possible to add (insert) multiple items at once?

I want to be able to clear the list and, in essence, provide a new array of 'initial values', but have not figured out how to do it.

**Comment by ferencb** [comment]
@rblinzler You can do something like:

```
$('#listbox').jqListbox("clear"); // This is not required because setFromArray will overwrite the values
var data = [{"title":"Test"},{"title":"Test 2"}];
$('#listbox').jqListbox("setFromArray", data);
$('#listbox').jqListbox("render");
```

**Comment by rablinz** [comment]
@ferencb Thank you for the response.

I somehow missed 'setFromArray' in the documentation. Worked perfectly.

**Comment by rablinz** [comment]
Not sure if this is what @vjuser was asking, but I would like to call 'Disable' on the list or table so that the user is prevented from selecting any item.

**Comment by ferencb** [comment]
It is not the same @rblinzler. You can disable your buttons (e.g. insert, update, delete) manually.

If you would like to disable the selection of the elements please submit a new issue on GitHub with that feature explained and I will implement it. Thank you!

**Comment by ferencb** [comment]
Closing this issue as no answer to my question.
@vjuser If still valid please re-open a new issue with detailed requirement for the feature. Thank you!
