### ISSUE TITLE
Ability to disable selection (e.g. onBeforeSelect event)

### ISSUE THREAD

**Issue by rablinz** [ferencb/jqlistbox#14]
Thank you for a great plugin.

One feature that I would like to see is a 'Disable' function or property that would disable the list/table. Ideally this would prevent an item from being selected (css properties from changing, checkboxes in table row from being checked, etc.), would, or would allow me to, specify cursor: default, opacity: .5 etc.

many thanks.

**Comment by ferencb** [comment]
Hi @rblinzler,

I've updated the plugin to version 1.3. Now you can use the onBeforeSelect and onBeforeDeSelect callbacks: return false if you want to avoid selection or deselection.

**Comment by rablinz** [comment]
Hi @ferencb ,
Thank you! This helps. Great tool!
